### ISSUE TITLE
[BUG] No steam installed error

### ISSUE THREAD

**Issue by DFlowD31** [sw2719/steam-account-switcher#47]
Hi, I have been following this for a while now and today when I re-installed my Windows, I got this Failed to read registry value error.

I have tried new downloads from the github and still the same. Steam is already installed in the system but cannot seem to find it.

**Comment by sw2719** [comment]
Hello, to understand your problem, let me ask a few questions.

1. Have you been using the program before reinstalling Windows?

2. Since you said you reinstalled Windows, is your situation:

A. Installed Steam with official installer after installing Windows

B. Steam is installed on data drive (or partition) so didn't install Steam

**Comment by Vizard53** [comment]
I think you have the same problem as me.
Installed Windows 11 (previously installed 10)
Installed Steam, logged in.
I started Switcher, an error appeared
Failed to read registry value.
Make sure that steam is installed.
I tried to install Steam and run it as an admin, installed it in different places, on different disks
Steam Account Switcher tried both previously installed and downloaded the latter from GitHub
(sorry for google translate)

**Comment by sw2719** [comment]
Check #48 for updates

**Comment by sw2719** [comment]
Check #49 for updates

**Comment by sw2719** [comment]
Should be fixed in v2.7.
