### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DarkAssassin48** [sw2719/steam-account-switcher#55]
![IoWYh8MQeA](https://user-images.githubusercontent.com/40138340/180856555-56fae071-f4b0-44f0-ba26-2f2fc7d6e840.jpg)

Can't open, gives error
![image](https://user-images.githubusercontent.com/40138340/180855962-948179ee-09a1-46eb-942b-72ced06d071f.png)

**Comment by sw2719** [comment]
Where do you have Steam installed? Is it `I:\Steam`?

**Comment by DarkAssassin48** [comment]
> Where do you have Steam installed? Is it `I:\Steam`?

Yes, my ssd 2

**Comment by sw2719** [comment]
Assuming that Steam installation path is indeed I:\Steam, you haven't taken any screenshots on that account yet. That's why it says the directory doesn't exist. I will add handling for this case in later version.

Or if you did take screenshots on that account, login to that account, open any screenshot folder of any game via Steam (Manage screenshots > View on disk) and copy the path and post it here.
