### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by z1zber** [sw2719/steam-account-switcher#57]
each as how I enter this application, a N / A label appears on all accounts
![image](https://user-images.githubusercontent.com/119687107/205329200-2a07875d-151a-4b00-9859-0d3d5bb43ae2.png)

**Comment by sw2719** [comment]
Assuming that there wasn't a change in how Steam saves profile datas, Profile picture and name being N/A means there's no profile info of that account saved in loginusers.vdf file. Since that info is saved the first time you log in to a account, it means you haven't logged in to that account once. Even if you did log in to the account but N/A would still show up, there's nothing I can do since it's Steam that is not functioning correctly.
