### ISSUE TITLE
It's absolutely not working on win7?

### ISSUE THREAD

**Issue by Freybjorn** [sw2719/steam-account-switcher#60]
On Win7 x64 i get error about .dll of VC++ (for sure they are installed)
![screenshot_1632](https://user-images.githubusercontent.com/36424288/225061040-0fd07990-ec60-4dfa-90ce-114558e629af.jpg)

**Comment by sw2719** [comment]
Hello, sorry to hear that it's not working. Unfortunately, as written in README's Requirements section, Windows 8.1 or newer is required to run the program since executable files are packaged with Python 3.10 which doesn't run on Windows 7.

You have two options:
* Upgrade to Windows 10
  - Security updates and technical support for Windows 7 ended on 2020. Maybe it's time to upgrade.
* Install Python 3.8 (which runs on Windows 7), setup the dependencies, and run the source file itself.
  - If you are not able to upgrade to Windows 10, this is the only option you have. Older releases (v2.6.1 or older) had used Python 3.8, however they were broken in a recent Steam update so it doesn't work anymore.

Sorry that I couldn't help, but those are your only options.
